package com.spheres.agiletrack.app;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Dashboard extends CssLayout {
	protected Label billing_header_label;
	protected CssLayout dashgraphics;
	protected CssLayout dashboardpane;
	protected CssLayout dashboardmaps;

	public Dashboard() {
		Design.read(this);
	}
}
