package com.spheres.agiletrack.view;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainView extends VerticalLayout {
	protected CssLayout header_bar;
	protected MenuBar menuBar;
	protected TextField search_field;
	protected HorizontalLayout main_area;
	protected CssLayout side_bar;
	protected NativeButton btDashboard;
	protected NativeButton btUnidades;
	protected NativeButton btReportes;
	protected NativeButton btMaps;
	protected NativeButton menuButton6;
	protected NativeButton btStarLink;
	protected NativeButton menuButton7;
	protected NativeButton btConfig;
	protected Panel scroll_panel;

	public MainView() {
		Design.read(this);
	}
}
